version: '3'

tasks:
  generate-api:
    desc: Генерация api сервера
    cmds:
      - oapi-codegen --config=oapi-codegen.yaml api/v1/openapi.yaml
  run-dev-server:
    desc: Запуск приложения
    cmds:
      - go run cmd/server/main.go
  build-push-latest:
    desc: Сборка и отправка в registry
    cmds:
      - docker build -f ./deployments/Dockerfile -t ghcr.io/clowngeo/ns-manager:latest .
      - docker push ghcr.io/clowngeo/ns-manager:latest